"""Initial database migration

Revision ID: 06db76eab812
Revises: 
Create Date: 2025-01-22 14:53:34.605891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06db76eab812'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.String(length=120), nullable=False),
    sa.Column('base_curriculums', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_content_id'), ['content_id'], unique=True)

    op.create_table('curriculum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.String(length=120), nullable=False),
    sa.Column('task_list', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_curriculum_id'), ['curriculum_id'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_key', sa.String(length=120), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('hint_1', sa.Text(), nullable=True),
    sa.Column('hint_2', sa.Text(), nullable=True),
    sa.Column('spec', sa.Text(), nullable=True),
    sa.Column('test', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video', sa.String(length=500), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_task_key'), ['task_key'], unique=True)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_key', sa.String(length=120), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('question', sa.String(length=200), nullable=True),
    sa.Column('answer', sa.String(length=120), nullable=True),
    sa.Column('distractor_1', sa.String(length=120), nullable=True),
    sa.Column('distractor_2', sa.String(length=120), nullable=True),
    sa.Column('distractor_3', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video', sa.String(length=500), nullable=True),
    sa.Column('video_start', sa.Integer(), nullable=True),
    sa.Column('video_end', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_task_key'), ['task_key'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('classroom_codes', sa.String(length=120), nullable=True),
    sa.Column('assigned_curriculums', sa.JSON(), nullable=True),
    sa.Column('assigned_content', sa.JSON(), nullable=True),
    sa.Column('special_curriculums', sa.JSON(), nullable=True),
    sa.Column('completed_curriculums', sa.JSON(), nullable=True),
    sa.Column('content_scores', sa.JSON(), nullable=True),
    sa.Column('correct_answers', sa.JSON(), nullable=True),
    sa.Column('current_curriculum', sa.String(length=120), nullable=True),
    sa.Column('current_question', sa.String(length=120), nullable=True),
    sa.Column('curriculum_scores', sa.JSON(), nullable=True),
    sa.Column('incorrect_answers', sa.JSON(), nullable=True),
    sa.Column('xp', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_assigned_content'), ['assigned_content'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_assigned_curriculums'), ['assigned_curriculums'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_classroom_codes'), ['classroom_codes'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_special_curriculums'), ['special_curriculums'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_codes', sa.JSON(), nullable=True),
    sa.Column('custom_curriculums', sa.JSON(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dXP', sa.Float(), nullable=True),
    sa.Column('question_id', sa.String(length=120), nullable=True),
    sa.Column('curriculum_id', sa.String(length=50), nullable=True),
    sa.Column('elapsed_time', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classroom_code'), ['code'], unique=True)

    op.create_table('classroom_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classroom_user')
    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_code'))

    op.drop_table('classroom')
    op.drop_table('xp')
    op.drop_table('admin')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_special_curriculums'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_classroom_codes'))
        batch_op.drop_index(batch_op.f('ix_user_assigned_curriculums'))
        batch_op.drop_index(batch_op.f('ix_user_assigned_content'))

    op.drop_table('user')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_task_key'))

    op.drop_table('questions')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_task_key'))

    op.drop_table('projects')
    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_curriculum_id'))

    op.drop_table('curriculum')
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_content_id'))

    op.drop_table('content')
    # ### end Alembic commands ###
