
"""added Admins, Classrooms, and ClassroomUser tables

Revision ID: 1c71bb24980c
Revises: ba6827b08085
Create Date: 2025-01-03 17:44:47.379639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c71bb24980c'
down_revision = 'ba6827b08085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_codes', sa.JSON(), nullable=True),
    sa.Column('custom_curriculums', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classroom_code'), ['code'], unique=True)

    op.create_table('classroom_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('classroom_codes', sa.String(length=120), nullable=True))
        batch_op.drop_index('ix_user_classroom_code')
        batch_op.create_index(batch_op.f('ix_user_classroom_codes'), ['classroom_codes'], unique=False)
        batch_op.drop_column('classroom_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_code', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_classroom_codes'))
        batch_op.create_index('ix_user_classroom_code', ['classroom_code'], unique=False)
        batch_op.drop_column('classroom_codes')
        batch_op.drop_column('role')

    op.drop_table('classroom_user')
    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_code'))

    op.drop_table('classroom')
    op.drop_table('admin')
    # ### end Alembic commands ###
