"""Removed unused columns from database

Revision ID: 2c4ff02e0758
Revises: 9a3f0a649252
Create Date: 2025-03-10 16:28:31.038938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '2c4ff02e0758'
down_revision = '9a3f0a649252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('classroom_codes')
        batch_op.drop_column('custom_curriculums')

    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.drop_column('assigned_content')

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('base_curriculums')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('content_scores')
        batch_op.drop_column('incorrect_answers')
        batch_op.drop_column('curriculum_scores')
        batch_op.drop_column('xp')
        batch_op.drop_column('correct_answers')
        batch_op.drop_column('completed_curriculums')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('completed_curriculums', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('correct_answers', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('xp', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('curriculum_scores', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('incorrect_answers', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('content_scores', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_curriculums', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_content', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_curriculums', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('classroom_codes', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
