"""removed creator_id for Content table

Revision ID: 3a6d48af6876
Revises: bbe5eaedc8f7
Create Date: 2025-01-26 11:54:19.449186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6d48af6876'
down_revision = 'bbe5eaedc8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
