"""Setting created_by foreign key to admin.id

Revision ID: 541d3b1580e2
Revises: 5b320e0f15fb
Create Date: 2025-01-26 12:10:29.011789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541d3b1580e2'
down_revision = '5b320e0f15fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_content_creator', 'admin', ['creator_id'], ['id'])

    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_curriculum_creator', 'admin', ['creator_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_projects_creator', 'admin', ['creator_id'], ['id'])

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_questions_creator', 'admin', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_content_creator', type_='foreignkey')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_curriculum_creator', type_='foreignkey')

    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_creator', type_='foreignkey')

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_constraint('fk_questions_creator', type_='foreignkey')

    # ### end Alembic commands ###
