"""Creating relational structure for course content

Revision ID: 551fdeae0854
Revises: 9e341c1f1293
Create Date: 2025-02-02 17:41:12.012349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '551fdeae0854'
down_revision = '9e341c1f1293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classroom_curriculum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_curriculum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_curriculum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.drop_column('task_list')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_assigned_content')
        batch_op.drop_index('ix_user_assigned_curriculums')
        batch_op.drop_index('ix_user_classroom_codes')
        batch_op.drop_index('ix_user_special_curriculums')
        batch_op.drop_column('current_question')
        batch_op.drop_column('assigned_curriculums')
        batch_op.drop_column('incorrect_answers')
        batch_op.drop_column('classroom_codes')
        batch_op.drop_column('correct_answers')
        batch_op.drop_column('content_scores')
        batch_op.drop_column('curriculum_scores')
        batch_op.drop_column('special_curriculums')
        batch_op.drop_column('current_curriculum')
        batch_op.drop_column('completed_curriculums')
        batch_op.drop_column('assigned_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_content', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('completed_curriculums', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('current_curriculum', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('special_curriculums', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('curriculum_scores', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('content_scores', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('correct_answers', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('classroom_codes', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('incorrect_answers', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('assigned_curriculums', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('current_question', sa.VARCHAR(length=120), nullable=True))
        batch_op.create_index('ix_user_special_curriculums', ['special_curriculums'], unique=False)
        batch_op.create_index('ix_user_classroom_codes', ['classroom_codes'], unique=False)
        batch_op.create_index('ix_user_assigned_curriculums', ['assigned_curriculums'], unique=False)
        batch_op.create_index('ix_user_assigned_content', ['assigned_content'], unique=False)

    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_list', sqlite.JSON(), nullable=True))

    op.drop_table('user_curriculum')
    op.drop_table('user_content')
    op.drop_table('curriculum_question')
    op.drop_table('curriculum_project')
    op.drop_table('content_curriculum')
    op.drop_table('classroom_curriculum')
    op.drop_table('classroom_content')
    # ### end Alembic commands ###
