"""Putting creator_id back in for Content table

Revision ID: 5b320e0f15fb
Revises: 3a6d48af6876
Create Date: 2025-01-26 11:56:13.413341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b320e0f15fb'
down_revision = '3a6d48af6876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
