
"""added added the role column to the Admin table

Revision ID: 61a35d12c856
Revises: 1c71bb24980c
Create Date: 2025-01-04 10:38:34.942108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a35d12c856'
down_revision = '1c71bb24980c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
