"""Initial migrate to fix Questions

Revision ID: 8f9525b74744
Revises: 
Create Date: 2025-02-16 14:20:18.173230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9525b74744'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('standard', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('objective', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('objective')
        batch_op.drop_column('standard')
        batch_op.drop_column('content_id')

    # ### end Alembic commands ###
