"""Add standard and objective to xp

Revision ID: 9a3f0a649252
Revises: 8f9525b74744
Create Date: 2025-02-19 17:39:41.362302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3f0a649252'
down_revision = '8f9525b74744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standard', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('objective', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xp', schema=None) as batch_op:
        batch_op.drop_column('objective')
        batch_op.drop_column('standard')

    # ### end Alembic commands ###
