"""Changed classroom_codes in user to JSON with [] default

Revision ID: 9e341c1f1293
Revises: 541d3b1580e2
Create Date: 2025-02-01 21:34:08.399774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e341c1f1293'
down_revision = '541d3b1580e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('classroom_codes',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('classroom_codes',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
