
"""Added classroom_code to users

Revision ID: b49d8b2a763f
Revises: f7d30e6da4de
Create Date: 2024-12-29 11:58:33.671181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49d8b2a763f'
down_revision = 'f7d30e6da4de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_code', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_classroom_code'), ['classroom_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_classroom_code'))
        batch_op.drop_column('classroom_code')

    # ### end Alembic commands ###
