"""removed role from User table - keeping in Admin table

Revision ID: bbe5eaedc8f7
Revises: 9fb224c4fe25
Create Date: 2025-01-22 17:07:16.272688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe5eaedc8f7'
down_revision = '9fb224c4fe25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
