"""empty message

Revision ID: d1333bdd07cc
Revises: 
Create Date: 2024-12-21 15:10:30.183222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1333bdd07cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('assigned_curriculums', sa.JSON(), nullable=True),
    sa.Column('completed_curriculums', sa.JSON(), nullable=True),
    sa.Column('content_scores', sa.JSON(), nullable=True),
    sa.Column('correct_answers', sa.JSON(), nullable=True),
    sa.Column('current_curriculum', sa.String(length=120), nullable=True),
    sa.Column('current_question', sa.String(length=120), nullable=True),
    sa.Column('curriculum_scores', sa.JSON(), nullable=True),
    sa.Column('incorrect_answers', sa.JSON(), nullable=True),
    sa.Column('questions_list', sa.JSON(), nullable=True),
    sa.Column('xp', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('xp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dXP', sa.Float(), nullable=True),
    sa.Column('question_id', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xp')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
