
"""Added content curriculum question tables

Revision ID: d2bb310bbb08
Revises: d1333bdd07cc
Create Date: 2024-12-26 15:42:12.120827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'd2bb310bbb08'
down_revision = 'd1333bdd07cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.String(length=120), nullable=False),
    sa.Column('base_curriculums', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_content_id'), ['content_id'], unique=True)

    op.create_table('curriculum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.String(length=120), nullable=False),
    sa.Column('questions_list', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_curriculum_id'), ['curriculum_id'], unique=True)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_key', sa.String(length=120), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('question', sa.String(length=200), nullable=True),
    sa.Column('answer', sa.String(length=120), nullable=True),
    sa.Column('distractor_1', sa.String(length=120), nullable=True),
    sa.Column('distractor_2', sa.String(length=120), nullable=True),
    sa.Column('distractor_3', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video', sa.String(length=500), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_question_key'), ['question_key'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_content', sa.JSON(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=254),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_user_assigned_content'), ['assigned_content'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_assigned_curriculums'), ['assigned_curriculums'], unique=False)
        batch_op.drop_column('questions_list')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questions_list', sqlite.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_assigned_curriculums'))
        batch_op.drop_index(batch_op.f('ix_user_assigned_content'))
        batch_op.alter_column('email',
               existing_type=sa.String(length=254),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('assigned_content')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_question_key'))

    op.drop_table('questions')
    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_curriculum_id'))

    op.drop_table('curriculum')
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_content_id'))

    op.drop_table('content')
    # ### end Alembic commands ###
