"""Removed classroomcurriculum table

Revision ID: d429841c9490
Revises: 2c4ff02e0758
Create Date: 2025-03-10 16:33:03.363425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd429841c9490'
down_revision = '2c4ff02e0758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classroom_curriculum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_curriculum',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('classroom_id', sa.INTEGER(), nullable=False),
    sa.Column('curriculum_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
