
"""Added Projects table

Revision ID: f7d30e6da4de
Revises: 7ba7551c4739
Create Date: 2024-12-29 11:39:18.629280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f7d30e6da4de'
down_revision = '7ba7551c4739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_key', sa.String(length=120), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('hint_1', sa.Text(), nullable=True),
    sa.Column('hint_2', sa.Text(), nullable=True),
    sa.Column('spec', sa.Text(), nullable=True),
    sa.Column('test', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video', sa.String(length=500), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_task_key'), ['task_key'], unique=True)

    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_list', sa.JSON(), nullable=True))
        batch_op.drop_column('questions_list')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_key', sa.String(length=120), nullable=False))
        batch_op.drop_index('ix_questions_question_key')
        batch_op.create_index(batch_op.f('ix_questions_task_key'), ['task_key'], unique=True)
        batch_op.drop_column('question_key')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_curriculums', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_special_curriculums'), ['special_curriculums'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_special_curriculums'))
        batch_op.drop_column('special_curriculums')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_key', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_index(batch_op.f('ix_questions_task_key'))
        batch_op.create_index('ix_questions_question_key', ['question_key'], unique=1)
        batch_op.drop_column('task_key')

    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questions_list', sqlite.JSON(), nullable=True))
        batch_op.drop_column('task_list')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_task_key'))

    op.drop_table('projects')
    # ### end Alembic commands ###
