"""Put the user performance back in the User table

Revision ID: f97f74b1d884
Revises: 551fdeae0854
Create Date: 2025-02-03 19:11:25.012191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97f74b1d884'
down_revision = '551fdeae0854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_curriculums', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('content_scores', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('correct_answers', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('current_curriculum', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('current_question', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('curriculum_scores', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('incorrect_answers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('incorrect_answers')
        batch_op.drop_column('curriculum_scores')
        batch_op.drop_column('current_question')
        batch_op.drop_column('current_curriculum')
        batch_op.drop_column('correct_answers')
        batch_op.drop_column('content_scores')
        batch_op.drop_column('completed_curriculums')

    # ### end Alembic commands ###
